[general]
import = [
    # from https://github.com/alacritty/alacritty-theme
    "~/.config/alacritty/themes/themes/gnome_terminal.toml"
]

[font]
size = 9.0

[font.bold]
family = "ComicShannsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "ComicShannsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "ComicShannsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "ComicShannsMono Nerd Font Mono"
style = "Regular"
